// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfrixrqrwgimlcchkopl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmcml4cnFyd2dpbWxjY2hrb3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzExMDksImV4cCI6MjA2NzgwNzEwOX0.ubZvZO7fIfkZVXkqg5SNhpQ7hquvn2LVrMDRxcjUlhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});